### PR TITLE
Upgrade to pureconfig 0.9.0

### PR DESCRIPTION
**Pull request by liff**
Mixing cats 1.0 and pureconfig 0.8 doesn't work too well.

### CODE REVIEW

**Comment by fthomas** [comment]
LGTM, thanks @liff!

**Comment by liff** [comment]
Any chance of 0.8.7 release with this? Right now, refined-cats 0.8.6 depends on cats 1.0 but pureconfig-cats 0.8.0 depends on cats 0.9.

**Comment by fthomas** [comment]
I'll try to release 0.8.7 this weekend.

**Comment by fthomas** [comment]
@liff 0.8.7 has been released.

**Comment by liff** [comment]
Thanks!

**Pull request merged**
