### PR TITLE
Bump sbt-doctest to 0.6.0

### PR DESCRIPTION
**Pull request by frgomes**
Please advise if https://github.com/tkawachi/sbt-doctest/issues/52 can be closed.
/cc @tkawachi

### CODE REVIEW

**Comment by fthomas** [comment]
Thanks! If this is supposed to run the doctests in JS, then this line needs to be removed too: https://github.com/fthomas/refined/blob/1b659a157844b3fbaf5ecd77302809a682fae2a5/build.sbt#L267 :-)

**Comment by frgomes** [comment]
@fthomas I've removed the configuration you pointed out and it gives me:
```
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/api/RefTypeDoctest.scala:15: You may not export a local class
[error]   include(new org.scalacheck.Properties("refine") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/api/RefTypeDoctest.scala:27: You may not export a local class
[error]   include(new org.scalacheck.Properties("refineM") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/api/RefTypeDoctest.scala:39: You may not export a local class
[error]   include(new org.scalacheck.Properties("refineMF") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/api/RefTypeDoctest.scala:51: You may not export a local class
[error]   include(new org.scalacheck.Properties("applyRef") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/api/RefTypeDoctest.scala:65: You may not export a local class
[error]   include(new org.scalacheck.Properties("applyRefM") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/autoDoctest.scala:15: You may not export a local class
[error]   include(new org.scalacheck.Properties("autoInfer") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/autoDoctest.scala:30: You may not export a local class
[error]   include(new org.scalacheck.Properties("autoUnwrap") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/numericDoctest.scala:15: You may not export a local class
[error]   include(new org.scalacheck.Properties("numeric") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/packageDoctest.scala:15: You may not export a local class
[error]   include(new org.scalacheck.Properties("W") {
[error]               ^
[error] /home/rgomes/workspace/refined/modules/core/js/target/scala-2.12/src_managed/test/eu/timepit/refined/util/stringDoctest.scala:15: You may not export a local class
[error]   include(new org.scalacheck.Properties("regex") {
[error]               ^
[error] 10 errors found
```

I'm not the best person to tell what would be the root cause of these errors.
  1. I don't use ScalaJS on a regular basis;
  2. I only use uTest, without any other test framework.
  3. In regards to sbt-doctest, I don't use property checks since they are dependent on ScalaCheck and... as I said, I avoid anything that could imply pulling any other dependencies.

**Comment by fthomas** [comment]
The errors indicate that sbt-doctest's `ScalaCheckGen` produces code that is not compatible with Scala.js. I would say this is what https://github.com/tkawachi/sbt-doctest/issues/52 is about.

refined doesn't use property tests in doctests, so it could be possible to run them on JS with a different test framework. Probably by setting `doctestTestFramework := DoctestTestFramework.MicroTest` in `moduleJsSettings`.
But I'm not sure if running the doctests on JS is worth a new test dependency. In refined's case the doctests do not test code that is not already covered by the ordinary ScalaCheck tests. So I'm okay with merging this with your last commit reverted.

**Comment by frgomes** [comment]
I've employed uTest in this tentative.
I had to disable fatal warnings in order to make the compilation pass.

/cc @tkawachi

Below we can see one of the offending files generated by ``sbt-doctest``.
The root cause of compilation warnings is that a ``import a.b.c`` is being generated when we are already in the context of ``package a.b.c``.

```scala
package eu.timepit.refined.api

import utest._

object RefTypeDoctest extends TestSuite {

    val tests = this {

  def sbtDoctestTypeEquals[A](a1: => A)(a2: => A): Unit = ()
  def sbtDoctestReplString(any: Any): String = {
    val s = scala.runtime.ScalaRunTime.replStringOf(any, 1000).init
    if (s.headOption == Some('\n')) s.tail else s
  }

  "RefType.scala:34: refine"-{
    import eu.timepit.refined.api.{ Refined, RefType }
    import eu.timepit.refined.numeric.Positive

    "example at line 43: RefType[Refined].refine[Positive](10)"-{
                  val _actual_   = sbtDoctestReplString(RefType[Refined].refine[Positive](10))
                  val _expected_ = "Right(10)"
      assert( _expected_ == _actual_ ) // 
      sbtDoctestTypeEquals(RefType[Refined].refine[Positive](10))((RefType[Refined].refine[Positive](10)): Either[String, Refined[Int, Positive]])
    }
  }

  "RefType.scala:54: refineM"-{
    import eu.timepit.refined.api.{ Refined, RefType }
    import eu.timepit.refined.numeric.Positive

    "example at line 62: RefType[Refined].refineM[Positive](10)"-{
                  val _actual_   = sbtDoctestReplString(RefType[Refined].refineM[Positive](10))
                  val _expected_ = "10"
      assert( _expected_ == _actual_ ) // 
      sbtDoctestTypeEquals(RefType[Refined].refineM[Positive](10))((RefType[Refined].refineM[Positive](10)): Refined[Int, Positive])
    }
  }

  "RefType.scala:75: refineMF"-{
    import eu.timepit.refined.api.{ Refined, RefType }
    import eu.timepit.refined.numeric.Positive

    "example at line 83: RefType[Refined].refineMF[Long, Positive](10)"-{
                  val _actual_   = sbtDoctestReplString(RefType[Refined].refineMF[Long, Positive](10))
                  val _expected_ = "10"
      assert( _expected_ == _actual_ ) // 
      sbtDoctestTypeEquals(RefType[Refined].refineMF[Long, Positive](10))((RefType[Refined].refineMF[Long, Positive](10)): Refined[Long, Positive])
    }
  }

  "RefType.scala:111: applyRef"-{
    import eu.timepit.refined.api.{ Refined, RefType }
    import eu.timepit.refined.numeric.Positive

    type PosInt = Int Refined Positive

    "example at line 121: RefType.applyRef[PosInt](10)"-{
                  val _actual_   = sbtDoctestReplString(RefType.applyRef[PosInt](10))
                  val _expected_ = "Right(10)"
      assert( _expected_ == _actual_ ) // 
      sbtDoctestTypeEquals(RefType.applyRef[PosInt](10))((RefType.applyRef[PosInt](10)): Either[String, PosInt])
    }
  }

  "RefType.scala:132: applyRefM"-{
    import eu.timepit.refined.api.{ Refined, RefType }
    import eu.timepit.refined.numeric.Positive

    type PosInt = Int Refined Positive

    "example at line 141: RefType.applyRefM[PosInt](10)"-{
                  val _actual_   = sbtDoctestReplString(RefType.applyRefM[PosInt](10))
                  val _expected_ = "10"
      assert( _expected_ == _actual_ ) // 
      sbtDoctestTypeEquals(RefType.applyRefM[PosInt](10))((RefType.applyRefM[PosInt](10)): PosInt)
    }
  }

    }
}
```

**Comment by frgomes** [comment]
BEWARE: The build pass, but I had to disable fatal warnings, which is not what we want.
I've raised tkawachi/sbt-doctest#95

**Comment by fthomas** [comment]
I've been looking for the string `example at line 43` in the Travis build log but could only find it in the JVM tests. Are they µTests really executed? I'm also sceptical about the usage of `scala.runtime.ScalaRunTime.replStringOf` in the above `RefTypeDoctest`. In https://github.com/tkawachi/sbt-doctest/issues/52#issuecomment-163090195 @tkawachi notes that this is not available on the JS side.

**Comment by fthomas** [comment]
The first commit of this PR has been added to #315 so that we can have a sbt-doctest that is also built for sbt 1.0.0.

**Comment by fthomas** [comment]
Closing since refined is already updated to sbt-doctest 0.7.1 and I'm okay with not running doctest in the JS build.

**Pull request closed without merging**
