### PR TITLE
Move compiler-dependent code into a module

### LINKED ISSUE #207: Core depends on scala-compiler
The stuff in `generic` is cool. Like super-cool. However, a great deal of the time, you don't need the tremendous power that it provides for defining arbitrary tests. When this is the case, it's really a drag that pulling in refined pulls in `scala-compiler.jar`, as `scala-compiler.jar` is _huge_ (like 15mb). I know it's really a hassle to split projects up into modules, but it would really be great if `generic` was in its own module in order to shrink the disk-wise footprint of refined's dependency set.

### PR DESCRIPTION
**Pull request by clhodapp**
Fixes #207
I rejiggered the parts of the build related to binary dependency checking a bit and bumped the version to 0.7.0 (-SNAPSHOT), since the change is breaking.

### CODE REVIEW

**Comment by fthomas** [comment]
This looks great, @clhodapp. Thanks for taking care of this issue!

**Comment by clhodapp** [comment]
Thanks for merging! A release including this would be highly appreciated sooner rather than later, as I'm finding that I get classloading failures under Scala 2.12 with Typelevel Scala (that would be fixed by a release of this change).

**Comment by clhodapp** [comment]
Also :crossed_fingers: that I didn't break the release process. I _think_ it should work.

**Comment by fthomas** [comment]
I'll try to release 0.7.0 today or tomorrow. One thing I'd like to do before is to mark the dependency on `scala-reflect` also as "provided".

**Pull request merged**
