### PR TITLE
Update to ScalaCheck 1.13

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by etaty** [comment]
Hi,
Thanks for this great lib.
I am using scalacheck 1.13.
I got an error while mixing with 1.12 (as expected I suppose)
> java.lang.IncompatibleClassChangeError: Fatal execution error, caused by Found class org.scalacheck.Gen, but interface was expected
Do you have time to push a version with scalacheck 1.13?

**Comment by fthomas** [comment]
I was waiting for https://github.com/quasar-analytics/quasar to move to ScalaCheck 1.13. But this has not happened yet.

I'll merge this PR and make a release later this week. If there is a need for refined-scalacheck with a ScalaCheck 1.12 dependency I'll probably provide another artifact for this version.

/cc @jedesah

**Comment by fthomas** [comment]
@etaty refined 0.6.0 with a ScalaCheck 1.13.3 depedency has just been released.

**Comment by etaty** [comment]
thanks

**Pull request merged**
