### PR TITLE
Fix the links to the relevant Scala files

### PR DESCRIPTION
**Pull request by kyusu**
While browsing the README.md I noticed that the links to the Scala files in the "Provided Predicates" section are broken.

### CODE REVIEW

**Comment by fthomas** [comment]
Thanks for the PR, @kyusu. I broke the links while adding support for Scala 3 where I moved the source files to Scala version specific directories, e.g: https://github.com/fthomas/refined/blob/master/modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/boolean.scala
I'd prefer linking to these files instead of the files in the `predicate` package since the latter contain only forwarders to the real code in the former files.

**Comment by kyusu** [comment]
@fthomas
Thanks for looking at the pull request. I'll change the links!

**Review by fthomas — APPROVED** [review]
Thanks @kyusu!

**Comment by kyusu** [comment]
I've changed the links to `boolean`, `numeric` & `generic`.

**Pull request merged**
