### PR TITLE
Support scala.js 1.0

### PR DESCRIPTION
**Pull request by cquiroz**
This PR contains fixes to partially support Scala.js 1.0.0
There are some important notes
`scalaz` and `scopt` are ommited. The first requires some code changes and the second has a conflict on the way the `OS` object is used that conflicts with scala.js
`scoverage` was disabled as well
It should be possible to run this on 0.6.32 and dual release
How is release handled?

### CODE REVIEW

**Comment by fthomas** [comment]
Thanks @cquiroz! The release is done via sbt-ci-release.

**Comment by cquiroz** [comment]
I maybe able to make travis release both, sent an extra PR but of course testing will only happen on merge

**Comment by cquiroz** [comment]
Fixes #744

**Comment by fthomas** [comment]
I modified the build so that scalaz and scopt are only disabled for Scala.js 1.0. I'll merge when the build is green.

**Comment by cquiroz** [comment]
Thanks

**Pull request merged**
