### PR TITLE
Experiment: reorganize type class instances

### PR DESCRIPTION
**Pull request by fthomas**
This is an experiment to find out how moving `Validate` and `Inference` instances to the companions of the predicates affects the library.

### CODE REVIEW

**Comment by fthomas** [comment]
The current organization of type class instances will maybe be unsupported in the future, see https://github.com/scala/scala/pull/6226.

**Comment by howyp** [comment]
+1 for making this change. Could it go in 0.9?

Also it looks like you left the Boolean inference typeclasses in a separate trait - is there a reason they have to stay there?

**Comment by fthomas** [comment]
This experiment is not complete, that is the reason why some instances are still in traits.

If this works without breaking (too many) things, I'm fine with doing it in 0.9.

**Comment by fthomas** [comment]
Closing in favor of #438.

**Pull request closed without merging**
