### PR TITLE
Refined literals support for BigInt and BigDecimal

### PR DESCRIPTION
**Pull request by kusamakura**
From #36.

It should work fine for numeric predicates except `Equals`.
There seems to be some difficulty with obtaining a Validate instance for BigInt and BigDecimal.

### CODE REVIEW

**Comment by fthomas** [comment]
Looks great @kusamakura! Could you run `sbt scalafmt` and commit to fix the build failure?

**Comment by kusamakura** [comment]
@fthomas Sorry for the delay. I'm thinking of trying to make `Equals` work with BigInt and BigDecimal first, but just in case that that would be for another issue, I'll push fixes to the build failure.

**Comment by fthomas** [comment]
It seems that `Unliftable` is not available on 2.10, so you can't use that. And the "pattern var ... in method unapply is never used" warning in the 2.12 build seems to be bogus. I'm okay with commenting out the `"-Ywarn-unused:patvars"` option in `build.sbt` which should get rid of this warning.

**Comment by kusamakura** [comment]
@fthomas Sorry, I wasn't able to work on this last week. The previous commit builds fine now, but I'm not sure how to go about the code coverage error. (I don't know how it works, sorry.)

**Comment by kusamakura** [comment]
@fthomas I've read up on code coverage, but I'm not sure if scoverage can detect matchers in macros. It seems to do so since `RefineMacro.scala` is covered, but I can't seem to get it to see the matchers `LiteralMatchers.scala` being used in the tests I provided.

**Comment by fthomas** [comment]
@kusamakura I think the problem with the code coverage is caused by using `scala-2.11+` as directory component for `BigLiteralsSpec.scala`. Looking at the build log for 2.12 I can't find the string `BigLiterals` indicating that this test is not executed in the 2.12 build. AFAIK sbt does not support directories like `scala-2.11+` out of the box so you need to duplicate this test file for 2.11 and 2.12.

**Comment by kusamakura** [comment]
@fthomas That makes sense. Thank you so much for your patience! I'll push the changes in a jiffy.

**Comment by kusamakura** [comment]
Thanks again @fthomas. I learned a lot. :)

**Pull request merged**
