### PR TITLE
Drop case in Refined

### PR DESCRIPTION
**Pull request by dwijnand**
.. with before-and-after (newly created) spec changes

### CODE REVIEW

**Comment by dwijnand** [comment]
Btw, happy to iterate and tweak any minor detail, the intent of the change is my only goal.

**Comment by dwijnand** [comment]
Let me know what you want to do in terms of bincompat..

**Comment by fthomas** [comment]
MiMa complains about a lot of stuff that `case` brought in. Of those things, I think I only care about `scala.Serializable`. What do you think of the others?

**Comment by dwijnand** [comment]
I'm happy to recover `Serializable`.

The other one that's a shot-call on your part - do you want to provide `Refined.unapply`?

**Comment by fthomas** [comment]
Yes, `Refined.unapply` would be useful too.

**Comment by dwijnand** [comment]
Thanks to @ceedubs it seems this was already decided against in #57. Perhaps this alternative fix is more acceptable.

**Comment by dwijnand** [comment]
@fthomas Added `Refined.unapply`, squashed and pushed.

**Comment by fthomas** [comment]
Thanks @dwijnand! LGTM. So the only unsafe operations are now `Refined.unsafeApply` and `asInstanceOf`, right?

**Comment by dwijnand** [comment]
`Refined.unsafeApply` - yes. What do you mean by `asInstanceOf`? Can you show a code/repl snippet?

**Comment by fthomas** [comment]
```scala
scala> val x: Int Refined Positive = 5
x: eu.timepit.refined.api.Refined[Int,eu.timepit.refined.numeric.Positive] = 5

scala> x.asInstanceOf[Int Refined Negative]
res0: eu.timepit.refined.api.Refined[Int,eu.timepit.refined.numeric.Negative] = 5
```

**Comment by dwijnand** [comment]
Right.. yeah, that one too :)

**Comment by dwijnand** [comment]
Custom value classes don't have that problem.

**Comment by fthomas** [comment]
I'm wondering if we should make `Refined` a case class again by making it a [`sealed abstract case class`](https://gist.github.com/tpolecat/a5cb0dc9adeacc93f846835ed21c92d2). With this combination of keywords we don't get unsafe `apply` and `copy` methods.

**Comment by dwijnand** [comment]
Can't have sealed value classes, as value classes are final.

**Comment by fthomas** [comment]
Good catch, @dwijnand. I've heard that the value class aspect of `Refined` was a reason for not using refined in the first place since value classes can't be nested. Maybe `extends AnyVal` should be dropped from `Refined`.

**Comment by dwijnand** [comment]
Maybe value classes should be allowed to nest... :D

**Comment by fthomas** [comment]
I heard that is an easy change in scalac ;-)

**Pull request merged**
