### PR TITLE
Fix Rfc1918ClassBPrivateSpec incorrect matches

### LINKED ISSUE #795: Rfc1918ClassBPrivateSpec incorrect matches
[Rfc1918ClassBPrivateSpec](https://github.com/fthomas/refined/blob/e64f11c6f4bcb322ceac76da4011c7e993838f5b/modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala#L79) matches IPs out of RFC range.
For example, `172.222.171.197` will match.
This is caused by a missing escaping backslash before the latest dot in the regex.
Actually, the regex is `^172\.(15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31).+`, the latest dot is considered as a wildcard character because not escaped, so any IP with a second digit starting with characters 15 to 31 will match.

Adding a backslash before, solve the issue: `^172\.(15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)\.+`

Here is a scastie to test: https://scastie.scala-lang.org/ktfISeSZQNG9iLt7MvUg0g

May I send a PR?

Thanks.

### PR DESCRIPTION
**Pull request by jbenoit2011**
Fix #795

### CODE REVIEW

**Comment by jbenoit2011** [comment]
A test failed, but it does not seem related to my changes:
```
[info] + RefTypeRead.load success: OK, proved property.
1179Error: Option --foo failed when given '0'. Predicate failed: (0 > 0).
1180Usage: tests [options]
1181
1182  -f, --foo <value>  foo is a positive integer property
1183[info] + RefTypeRead.load failure (predicate): OK, proved property.
1184Error: Option --foo expects a number but was given 'abc'
1185Usage: tests [options]
1186
1187  -f, --foo <value>  foo is a positive integer property
```
It already happened on master.

**Comment by fthomas** [comment]
I think the error that failed the build is:
```
[warn] /home/travis/build/fthomas/refined/modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala isn't formatted properly!
[warn] /home/travis/build/fthomas/refined/modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala isn't formatted properly!
...
[error] 1 files must be formatted
[error] 1 files must be formatted
[error] (coreJS / Compile / scalafmtCheck) 1 files must be formatted
[error] (coreJVM / Compile / scalafmtCheck) 1 files must be formatted
```
Running `sbt scalafmtAll` should fix the formatting.

**Comment by jbenoit2011** [comment]
Didn't know about `scalafmtAll` command, thanks for telling me.
Everything seems ok now.
When do you plan the next release including this fix?
Thanks.

**Comment by fthomas** [comment]
I can make a release with this fix soon. But before I do, it may be worth looking into another issue with `Rfc1918ClassBPrivateSpec ` that is mentioned in #702:

> There is also a bug in Rfc1918ClassBPrivateSpec. It should start at 172.16.0.0 not 172.15.0.0. https://tools.ietf.org/html/rfc1918#section-3

WDYT @jbenoit2011?

**Comment by jbenoit2011** [comment]
I just pushed a patch to fix the start range of rfc1918 class b ips issue described in #702

**Pull request merged**
