### PR TITLE
Build with Scala 3.0.0-M2

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by tpolecat** [comment]
Haha I just came in here to see if you were working on M2! Nice timing.

**Comment by fthomas** [comment]
Actually I opened this now because I saw seeing you working on the scala-3 branch in doobie. :-)

**Comment by tpolecat** [comment]
GH is sucking it today. Actions are stalled everywhere. 💤

**Comment by fthomas** [comment]
refined 0.9.19 is now available for Scala 3.0.0-M1 and Scala 3.0.0-M2.

**Pull request merged**
