### PR TITLE
Update to sbt 1.0.0

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by fthomas** [comment]
Currently blocked by:
* [ ] sbt-scalajs-crossproject: https://github.com/scala-native/sbt-crossproject/issues/53
* [ ] scalastyle-sbt-plugin: https://github.com/scalastyle/scalastyle-sbt-plugin/issues/62

**Comment by matthewfarwell** [comment]
Release scalastyle v1.0.0 which has sbt 1.0 support.

**Comment by fthomas** [comment]
Thanks @matthewfarwell!

**Comment by fthomas** [comment]
The 2.10 builds failed because tut-core 0.6.0 is not available for 2.10. Tracking that here: https://github.com/tpolecat/tut/pull/180

**Pull request merged**
